export const weatherCodes = {
	0: 'Clear Sky',
	1: 'Mostly Clear',
	2: 'Partly Cloudy',
	3: 'Cloudy',
	45: 'Fog',
	48: 'Fog',
	51: 'Drizzle',
	53: 'Drizzle',
	55: 'Drizzle',
	56: 'Drizzle',
	57: 'Drizzle',
	61: 'Slight Rain',
	63: 'Moderate Rain',
	65: 'Heavy Rain',
	66: 'Light Rain',
	67: 'Heavy Rain',
	71: 'Light Snow',
	73: 'Moderate Snow',
	75: 'Heavy Snow',
	77: 'Snowing',
	80: 'Light Showers',
	81: 'Moderate Showers',
	82: 'Heavy Showers',
	85: 'Light Snow Showers',
	86: 'Heavy Snow Showers',
};
